/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.29
</auto-generated>
------------------------------------------------------------------------------ */

using Progress.Sitefinity.Renderer.Designers;
using Progress.Sitefinity.Renderer.Designers.Attributes;
using Progress.Sitefinity.Renderer.Entities.Content;
using SFDevSept2022.Mvc.Models;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;

namespace SFDevSept2022.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "HelloWorld", Title = "Hello World", SectionName = "SFDevSept2022")]
	public class HelloWorldController : Controller, IPersonalizable
	{
		// GET: HelloWorld
		public ActionResult Index()
		{
			var model = new HelloWorldModel();
			model.Message = this.Message;
            model.Flag = this.Flag;
            model.Enum = this.Enum;
            model.Number = this.Number;
            model.MyDate = this.MyDate;
            return View("Index", model);
		}

        public ActionResult Samuel()
        {

            return View("Samuel");
        }
		
        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

        public string Message { get; set; }
        public bool Flag { get; set; }
        public Enumeration Enum { get; set; }
        [Browsable(false)]
        public int Number { get; set; }
        public DateTime MyDate { get; set; }

        [DisplayName("My First Check Box")]
        [Group("Lino Group")]
        [DataType(customDataType: KnownFieldTypes.CheckBox)]
        public bool MyFirstCheckbox { get; set; }
        [DisplayName("My Second Check Box")]
        [Group("Lino Group")]
        [DataType(customDataType: KnownFieldTypes.CheckBox)]
        public bool MySecondCheckbox { get; set; }

        [Content(Type=KnownContentTypes.Images)]
        public MixedContentContext Images { get; set; }

        [Content(Type = KnownContentTypes.Pages, AllowMultipleItemsSelection =false)]
        public MixedContentContext Pages { get; set; }
    }
}