/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.22
</auto-generated>
------------------------------------------------------------------------------ */

using SFDev2022.Mvc.Models;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;

namespace SFDev2022.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "Lam", Title = "Lam", SectionName = "SFDev2022")]
	public class LamController : Controller, IPersonalizable
	{
		// GET: Lam
		public ActionResult Index()
		{
			var model = new LamModel();
			model.Message = this.Message;
			return View("Index", model);
		}
		
        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

		public string Message { get; set; }
	}
}