/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.22
</auto-generated>
------------------------------------------------------------------------------ */

using SFDev2022.Mvc.Models;
using System;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;

namespace SFDev2022.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "LinoWidget", Title = "Lino Widget", SectionName = "SFDev2022")]
	public class LinoWidgetController : Controller, IPersonalizable
	{
		// GET: LinoWidget
		public ActionResult Index()
		{
			var model = new LinoWidgetModel();
			model.Message = this.Message;
			model.Flag = this.Flag;
			model.Enum = this.Enum;
			model.Number = this.Number;
			model.MyDate = this.MyDate;
			return View("Index",model);
		}
		public ActionResult Nick()
        {

			return View("Nick");
        }
		
        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

		public string Message { get; set; }
		public bool Flag { get; set; }
		public Enumeration Enum { get; set; }
		public int Number { get; set; }
		public DateTime MyDate { get; set; }
	}
}